### ISSUE TITLE
unable to build release 

### ISSUE THREAD

**Issue by invisiblecoder99** [MoMoWait/LeanbackLauncher#1]
pleaze upload compiled apk

**Comment by MoMoWait** [comment]
You need compile it on Android 7.1 source code.

**Comment by invisiblecoder99** [comment]
@MoMoWait give me explainnation please

**Comment by invisiblecoder99** [comment]
please provide any instant messaging id like skype

**Comment by MoMoWait** [comment]
In the Android 7.1 source code，Use “mm” to make this project.
Wechat ID:GaoFei20171003

**Comment by invisiblecoder99** [comment]
added on we chat please check

**Comment by MoMoWait** [comment]
Sorrry, I didn't receive any requests

**Comment by invisiblecoder99** [comment]
add me on skype: quickstreamingmedia
